### ISSUE TITLE
JohnTheRipper formats

### ISSUE THREAD

**Issue by psypanda** [psypanda/hashID#20]
As requested on the [hashcat forum](http://hashcat.net/forum/thread-3399-post-22298.html#pid22298) hashID should also support the corresponding JohnTheRipper format/mode.

I already added some JTR formats to [hashinfo.xlsx](https://github.com/psypanda/hashID/blob/master/docs/hashinfo.xlsx) but I'm still missing a lot more.

**Comment by magnumripper** [comment]
This will give you a rough list of example hashes for JtR
```
$ ../run/john --list=format-details | cut -d"       " -f1,14 | column -t
```
(within the quotes is one tab, escaped with ctrl-v in bash)

Caveat: The hashes will be output truncated to 256 chars (24 formats affected) and the examples may or may not include a "format tag".

To investigate a single format, use eg.
```
$ ../run/john --list=format-tests --format:mssql | cut -f1,3
```
This will list all self-test-vectors for the format (actually you can list them for all formats at once if you drop the --format option) and they will not be truncated. If the format has a "tag" at all, it should always be included in at least one of the lines.

**Comment by psypanda** [comment]
Thank you. I've created two files from the commands and started working in the branch [jtr-formats](https://github.com/psypanda/hashID/tree/jtr-formats)
[format-details](http://pastebin.com/raw.php?i=GZr32xPS): `$ ../run/john --list=format-details | cut -f1,14 | column -t`
[format-tests](http://pastebin.com/raw.php?i=A3JSbdzm): `$ ../run/john --list=format-tests | cut -f1,3`

**Comment by magnumripper** [comment]
I see now the 'column -t' was a bad idea, you might want to regenerate it without that.

**Comment by psypanda** [comment]
Yeah I didn't mind that some hashes got messed up a little, but anyway [here](http://pastebin.com/raw.php?i=iw7qnRUK) is the new generated file `format-details` without `column -t`

**Comment by magnumripper** [comment]
Wow, found a bug here. Some formats (eg. NETNTLM) lacked ciphertexts in your output. The bug is fixed in bleeding-jumbo, please pull and re-generate that first file once again if needed.

**Comment by psypanda** [comment]
Oh wow, glad you could work that out. I'll create another list later from the latest pull

**Comment by psypanda** [comment]
Got the first quick and dirty working version out (9e4e3ff85cfae2bf47f7cc92ba1b8c32b6ecfd86).
Still some JtR formats need to be added and changed from the [new list generated from the latest pull from bleeding-jumbo](http://pastebin.com/raw.php?i=sNR8q8rb) - but its a start.

**Comment by magnumripper** [comment]
BTW I forgot to stress this: Please note that JtR very often has two (or more) valid *input* formats for any given hash type. One is what's written in the .pot file, that one nearly always has a "tag". But often other formats are accepted as *input*, typically the untagged format (like a raw hex string). For example, we accept NT hashes as untagged raw hex input (any hex string of length 32), or as pwdump format, or with the tag ($NT$deadcafebabeblablabla). For untagged input you typically need to specify --format while tagged input will be auto-detected.

Just so you have this straight, maybe you already knew all this.
