### ISSUE TITLE
hashid does not install in Arch linux

### ISSUE THREAD

**Issue by superbonaci** [psypanda/hashID#54]
This is the pip which I have installed:
```
$ sudo pacman -S python-pip
resolving dependencies...
looking for conflicting packages...

Packages (7) python-attrs-22.2.0-3  python-cffi-1.15.1-3  python-cryptography-41.0.2-1  python-ply-3.11-12
             python-pycparser-2.21-5  python-wheel-0.40.0-3  python-pip-23.1.2-1

Total Download Size:    4.82 MiB
Total Installed Size:  29.61 MiB
```
Why do I get this error:
```
$ pip install hashid
error: externally-managed-environment

× This environment is externally managed
?-> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

**Comment by superbonaci** [comment]
`pipx` does the job
[Handling Externally Managed Environment Error With Pip in Ubuntu 23.04](https://itsfoss.com/externally-managed-environment/)

please update documentation

**Comment by bburky** [comment]
That error is due to the configuration of your system Python installation from your Arch Linux distro, not a hashID issue. pipx or any other venv solution should resolve it, yes.

Also, this project is not really currently maintained. There have been a few recent forks though that are currently maintained. See this issue: https://github.com/psypanda/hashID/issues/50

**Comment by DrRac27** [comment]
There is also a package on the AUR: [hashid](https://aur.archlinux.org/packages/hashid)

**Comment by superbonaci** [comment]
> There is also a package on the AUR: [hashid](https://aur.archlinux.org/packages/hashid)

Last update is from 2018, hope it's still working.

**Comment by DrRac27** [comment]
If that bothers you you should better not look at the last update of hashid ^^
Also if it isn't working please tell me so I can fix it.

**Comment by superbonaci** [comment]
Install fine:
```
$ hashid --version
hashID v3.2.0-dev by c0re (https://github.com/psypanda/hashID)
```
